TOP_DIR = ../../../../../..
sinclude $(TOP_DIR)/tools/w800/conf.mk

GEN_LIBS = libossrc$(LIB_EXT)

#DEFINES +=

sinclude $(TOP_DIR)/tools/w800/rules.mk

INCLUDES := $(INCLUDES) -I $(PDIR)include
PDIR := ../$(PDIR)
sinclude $(PDIR)Makefile